version: '3'
services:
  stfw-kcov:
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - ./:/source
      - ./dist/tmp:/tmp
    command: /source/dist/out /source/build/product/integration_test.sh /source/dist/stfw-with-depends-0.2.0-SNAPSHOT.tar.gz
